version: '3'
services:
  db_pbh:
    image: mariadb:10.11
    container_name: pbh
    ports:
      - "4100:3306"
    volumes:
      - ~/docker_mysql/pbh:/var/lib/mysql/
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_ROOT_PASSWORD: ""
    command: --default-authentication-plugin=mysql_native_password